spring:
  datasource:
    # url: jdbc:mysql://172.16.0.11/report_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    # username: choerodon
    # password: 123456
    url: jdbc:postgresql://172.16.0.11:5432/odoo-enterprise2
    username: odoo
    password: odoo

  datasource1:
    # url: jdbc:mysql://172.16.0.11/report_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    # username: choerodon
    # password: 123456
    url: jdbc:postgresql://172.16.0.11:5432/postgres
    username: odoo
    password: odoo